/* AUTO-GENERATED by tools/lqr_gain_gen.py — do not edit by hand. */
#include "balance/balance_lqr_gain.h"

/* model: ra8t2_6p5in_hoverboard */
/* Q diag = [12.0, 1.0, 3.0, 0.4]  R = 4.0 */

float g_balance_theta_bias_rad = 0.0f;

const float BALANCE_LQR_K[2][4] = {
    /* common torque: firmware uses u += K[i]*x[i] (stores -K_classic) */
    { 427.39958283f, 69.94888439f, 0.86602540f, 0.62212262f },
    /* differential / yaw extension reserved */
    { 0.0f, 0.0f, 0.0f, 0.0f }
};
