#!/usr/bin/env python3
"""Generate balance_lqr_gain.c from robot physical parameters (continuous LQR).

4-state wheeled inverted-pendulum bootstrap model:
  x = [θ, θ̇, φ, φ̇]^T
  u = τ_common (N·m)

Usage:
  pip install -r tools/requirements.txt
  python3 tools/lqr_gain_gen.py
"""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
import yaml

ROOT = Path(__file__).resolve().parents[1]


def load_params(path: Path) -> dict:
    with path.open("r", encoding="utf-8") as f:
        return yaml.safe_load(f)


def build_ab(p: dict) -> tuple[np.ndarray, np.ndarray]:
    """Simplified planar WIP linearization about upright.

    Enough for gain bootstrapping; replace with identified A/B when available.
    """
    g = float(p["chassis"]["gravity"])
    m = float(p["chassis"]["mass_kg"])
    L = float(p["chassis"]["com_height_m"])
    Jb = float(p["chassis"]["body_pitch_inertia_kgm2"])
    r = float(p["wheel"]["radius_m"])
    n_w = int(p["wheel"]["count"])
    mw = float(p["wheel"]["mass_each_kg"]) * n_w
    Jw = float(p["wheel"]["inertia_each_kgm2"]) * n_w

    M11 = Jb + m * L * L
    M12 = m * L * r
    M21 = M12
    M22 = (m + mw) * r * r + Jw
    det = M11 * M22 - M12 * M21
    if abs(det) < 1e-9:
        raise RuntimeError("Singular mass matrix — check parameters")

    inv11 = M22 / det
    inv12 = -M12 / det
    inv21 = -M21 / det
    inv22 = M11 / det
    g_term = m * g * L

    # θ_ddot ≈ inv11*g_term*θ + inv12*τ
    # φ_ddot ≈ inv21*g_term*θ + (inv22/r)*τ
    A = np.array(
        [
            [0.0, 1.0, 0.0, 0.0],
            [inv11 * g_term, 0.0, 0.0, 0.0],
            [0.0, 0.0, 0.0, 1.0],
            [inv21 * g_term, 0.0, 0.0, 0.0],
        ],
        dtype=float,
    )
    B = np.array(
        [
            [0.0],
            [inv12],
            [0.0],
            [inv22 / r],
        ],
        dtype=float,
    )
    return A, B


def care_lqr(A: np.ndarray, B: np.ndarray, Q: np.ndarray, R: np.ndarray) -> np.ndarray:
    try:
        from scipy.linalg import solve_continuous_are
    except ImportError as e:
        raise SystemExit("scipy required: pip install -r tools/requirements.txt") from e
    P = solve_continuous_are(A, B, Q, R)
    K = np.linalg.solve(R, B.T @ P)
    return np.asarray(K, dtype=float)


def emit_c(path: Path, K: np.ndarray, meta: dict, q_diag, r_torque: float) -> None:
    if K.shape != (1, 4):
        raise RuntimeError(f"Expected K shape (1,4), got {K.shape}")

    text = "\n".join(
        [
            "/* AUTO-GENERATED by tools/lqr_gain_gen.py — do not edit by hand. */",
            '#include "balance/balance_lqr_gain.h"',
            "",
            f"/* model: {meta.get('name', 'unknown')} */",
            f"/* Q diag = {list(map(float, q_diag))}  R = {float(r_torque)} */",
            "",
            "float g_balance_theta_bias_rad = 0.0f;",
            "",
            "const float BALANCE_LQR_K[2][4] = {",
            "    /* common torque: firmware uses u += K[i]*x[i] (stores -K_classic) */",
            "    { " + ", ".join(f"{v:.8f}f" for v in K[0]) + " },",
            "    /* differential / yaw extension reserved */",
            "    { 0.0f, 0.0f, 0.0f, 0.0f }",
            "};",
            "",
        ]
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    print(f"Wrote {path}")
    print("K_fw =", K[0])


def main() -> None:
    ap = argparse.ArgumentParser(description="RA8T2 hoverboard LQR gain generator")
    ap.add_argument("--params", type=Path, default=ROOT / "params" / "robot_params.yaml")
    ap.add_argument(
        "--out",
        type=Path,
        default=ROOT / "firmware" / "src" / "balance" / "balance_lqr_gain.c",
    )
    args = ap.parse_args()

    p = load_params(args.params)
    A, B = build_ab(p)
    q_diag = np.array(p["control"]["q_diag"], dtype=float)
    r_torque = float(p["control"]["r_torque"])
    Q = np.diag(q_diag)
    R = np.array([[r_torque]], dtype=float)

    ctrb = np.hstack([B, A @ B, A @ A @ B, A @ A @ A @ B])
    print("A=\n", A)
    print("B=\n", B)
    print("ctrb rank=", np.linalg.matrix_rank(ctrb), "/4")

    K = care_lqr(A, B, Q, R)
    K_fw = -K  # match firmware u += Kx restoring convention after sign bring-up
    print("closed-loop eigs:", np.linalg.eigvals(A - B @ K))
    emit_c(args.out, K_fw, p.get("meta", {}), q_diag, r_torque)


if __name__ == "__main__":
    main()
